"""empty message

Revision ID: bc32d25a2d4f
Revises: 
Create Date: 2022-06-02 19:38:32.312223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc32d25a2d4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdn',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('body', sa.LargeBinary(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('comments',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('_picture', sa.JSON(), nullable=True),
    sa.Column('_owner', sa.String(length=64), nullable=False),
    sa.Column('_user', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('friends',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('_user1', sa.String(length=64), nullable=False),
    sa.Column('_user2', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('groups',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('_owner', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('entry', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groupshook',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('_user', sa.String(length=64), nullable=False),
    sa.Column('_group', sa.String(length=64), nullable=False),
    sa.Column('duty', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('posts',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('_user', sa.String(length=64), nullable=False),
    sa.Column('_shared', sa.String(length=64), nullable=True),
    sa.Column('_pictures', sa.JSON(), nullable=True),
    sa.Column('_privacity', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('profiles',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('_img', sa.String(length=64), nullable=False),
    sa.Column('_post', sa.String(length=64), nullable=False),
    sa.Column('_user', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('reacts',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('solicitations',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('_req', sa.String(length=64), nullable=False),
    sa.Column('_user', sa.String(length=64), nullable=True),
    sa.Column('_group', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('users',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('solicitations')
    op.drop_table('reacts')
    op.drop_table('profiles')
    op.drop_table('posts')
    op.drop_table('groupshook')
    op.drop_table('groups')
    op.drop_table('friends')
    op.drop_table('comments')
    op.drop_table('cdn')
    # ### end Alembic commands ###
